platformName=Android
deviceName=MyPixel9
automationName=UiAutomator2
appiumServer=http://127.0.0.1:4723
appPath=src/test/resources/apps/General-Store.apk
implicitWait=10
executionType=cloud
appPackage=in.org.npci.upi
appActivity=in.org.npci.upiapp.HomeActivity

#Cloud setup details
cloud.deviceName=realme C21 Y
cloud.platformVersion=11|15
cloud.appId=stock
cloud.network=false