platformName=Android
deviceName=MyPixel9
automationName=UiAutomator2
appiumServer=http://127.0.0.1:4723
appPath=src/test/resources/apps/General-Store.apk
implicitWait=10
executionType=cloud

#Cloud setup details
cloud.deviceName=.*
cloud.platformVersion=15
cloud.appId=lt://APP10160332171773416981259798